# fetch posts
WORD_LENGTH_MAX = 512 # set None to be unlimited
WORD_LENGTH_MIN = 12
LINE_LENGTH_MAX = 32
LINE_LENGTH_MIN = 2

# w2v setting
W2V_BY_VOCAB = True # if False: Create w2v model by each character
USE_START_MARK = True # if False: starting indicator would be zero vector
START_MARK = 'š'
USE_ENDING_MARK = True
ENDING_MARK = 'ê'
W2V_MIN_COUNT_BY_VOCAB = 10
W2V_MIN_COUNT_BY_CHAR = 4
W2V_ITER = 4
WV_SIZE = 100

# training data configure
ZERO_OFFSET = True
USE_SAVED_MODEL = False
SAVE_MODEL_NAME = "rnnstuck_model.h5"

# LSTM setting
MAX_TIMESTEP = 24 # set None to be unlimited
RNN_UNIT = [12]
USE_BIDIRECTION = True
USE_SEQ_RNN_OUTPUT = True
USE_ATTENTION = False
VOCAB_SIZE = -1
BATCH_SIZE = 96
EPOCHS = 200
VALIDATION_NUMBER = 100

OUTPUT_NUMBER = 4
OUTPUT_TIME_STEP = 100

STEP_EPOCH_RATE = 1.0
LEARNING_RATE = 0.002
LR_DECAY = 0.707
LR_DECAY_INTV = 2
LR_DECAY_POW_MAX = 8

EARLYSTOP_MIN_DELTA = 0.01
EARLYSTOP_PATIENCE = 4 if EPOCHS < 12 else int(EPOCHS / (4 * STEP_EPOCH_RATE))

